### ISSUE TITLE
Feature request: Add  p-value of the D-W test

### ISSUE THREAD

**Issue by tianliu88** [franzmohr/prais#14]
Thank you very much for using the package. I have a request: would it be possible to include the p-value of the D-W test in the summary output? I would greatly appreciate it.

tian liu

**Comment by franzmohr** [comment]
Hi Tian Liu! Just to let you know: I looked at the code of lmtest::dwtest and realised that this feature will be more difficult to implement than expected. So this might take a while, at least for me.
