### ISSUE TITLE
Return "lm" object from prais_winsten()

### ISSUE THREAD

**Issue by jlprol** [franzmohr/prais#5]
Thanks for this great package.

Is there any way to return an object of class "lm" rather than "prais" from `prais_winsten()` to work with other packages, such as {stargazer} and {broom}?

In the previous version of the function `prais.winsten()`, the `return()` function could be changed to "lm" (as explained here: https://stackoverflow.com/questions/49109282/how-to-work-with-prais-winsten-results-in-stargazer-and-broom-r), but that doesn't work anymore.

Thank you.

**Comment by franzmohr** [comment]
You could try to trick stargaze or broom by changing the class to using `class(pw_output) <- "lm"` after the estimation step. In the meantime I will look into how the packages might recognise prais-objects.

**Comment by franzmohr** [comment]
`stargazer` [does not seem to be developed much further](https://declaredesign.org/r/estimatr/articles/regression-tables.html). Issue #13 is a feature request for compatibility with `gtsummary`, which is also based on `broom`. So `prais` will go into this direction and this issues is combined with issue #13.
