### ISSUE TITLE
v1.1.2 Returns Error When Using Lagged Variables

### ISSUE THREAD

**Issue by sweetmoniker** [franzmohr/prais#7]
The following call yields the error "subscript out of bounds"
```
prais_winsten(Sales ~ January + Variable_L1, data = dataset, index = dataset$Date)
Iteration 0: rho = 0
Error in `[<-`(`*tmp*`, groups[[i]], 2, value = c((1 - rho[j]^2)^(1/2),  : 
  subscript out of bounds
```
If I run "prais_winsten(Sales ~ January + Variable, data = dataset, index = dataset$Date)" it works fine. Any lagged variable, i.e., for a 1 period lag the first observation = "NA" and the second is equal to observation 1, etc. causes this error.

I will disclose that this could be due to improper use of the "index." Index was not required in v1.1.1, so I've never had to use it before. Regardless, reverting to v1.1.1 solves the issue.

**Comment by franzmohr** [comment]
Sorry for the late reply, Monika! It seems that the index argument is not correctly specified. Did you try `index = "Date"`?

**Comment by sweetmoniker** [comment]
I did not try forming the index argument that way. "dataset$Date" and "Date" are the same thing; it seems silly if that would make a difference. As stated above "dataset$Date" worked with unlagged variables. Also as stated, my solution was to revert to 1.1.1 which did not present the error or require the index argument. Thanks!

**Comment by franzmohr** [comment]
I found that "dataset$Date" loads the entire column, so that the first elements of that column would be passed on as indices. So this should make a material difference. Please just try it with index = "Date".  In the updated version it is a saveguard, which ensures that the data is in correct order.

With respect to the NA error: Does it help if you delete all NAs from the input dataset?

**Comment by sweetmoniker** [comment]
Thanks for the update. No offense, but I'm not going to test either of those things, but you certainly can. These seem like shortfalls in version 1.1.2. The index issue is not present in v1.1.1, nor do I need to delete NAs from my dataset in v1.1.1. Reverting to 1.1.1 is my solution. Thanks for your time.

**Comment by franzmohr** [comment]
All good. The new index functionality follows the Stata logic, where it is mandatory to specify indices when using prais. Closing this issue then.
